# Main justfile to run all the development scripts
# To install 'just' see https://github.com/casey/just#installation

# Ensure all properties are exported as shell env-vars
set export

# set the current directory, and the location of the test dats
CWDIR := justfile_directory()

_default:
  @just -f {{justfile()}} --list

[no-cd]
build:
    #!/bin/bash
    set -ex -o pipefail
    mkdir -p _out
    xelatex -shell-escape -output-directory=_out main
    biber --output-directory _out main
    xelatex -shell-escape -output-directory=_out main
    xelatex -shell-escape -output-directory=_out main
