# Main justfile to run all the development scripts
# To install 'just' see https://github.com/casey/just#installation

# Ensure all properties are exported as shell env-vars
set export

# set the current directory, and the location of the test dats
CWDIR := justfile_directory()

_default:
  @just -f {{justfile()}} --list

[no-cd]
build:
    #!/bin/bash
    set -ex -o pipefail
    
    xelatex -shell-escape main
    biber main
    xelatex -shell-escape main
    xelatex -shell-escape main
